In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.0+cu124


In [2]:
random_tensor = torch.rand(7,3,4,1)
random_tensor

tensor([[[[0.2758],
          [0.4656],
          [0.3709],
          [0.1429]],

         [[0.0335],
          [0.7463],
          [0.8400],
          [0.3603]],

         [[0.9162],
          [0.1516],
          [0.2046],
          [0.0660]]],


        [[[0.8000],
          [0.2170],
          [0.4573],
          [0.5158]],

         [[0.2513],
          [0.2676],
          [0.9767],
          [0.8825]],

         [[0.7827],
          [0.9676],
          [0.7926],
          [0.4627]]],


        [[[0.9563],
          [0.6796],
          [0.4772],
          [0.9301]],

         [[0.8754],
          [0.5795],
          [0.5911],
          [0.5176]],

         [[0.9001],
          [0.2784],
          [0.5798],
          [0.2391]]],


        [[[0.3560],
          [0.9163],
          [0.3849],
          [0.8624]],

         [[0.2321],
          [0.2835],
          [0.1224],
          [0.6479]],

         [[0.7829],
          [0.8341],
          [0.5291],
          [0.6662]]],


        

In [3]:
random_tensor.shape

torch.Size([7, 3, 4, 1])

In [4]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
float_32_tensor = torch.tensor([3.0, 2.0, 1.0], 
                                dtype=torch.float32, 
                                device="cpu", 
                                requires_grad=False)



In [6]:
MATRIX_A = torch.tensor([[1,2], [3,4]])
MATRIX_B = torch.tensor([[5,6], [7,8]])
torch.matmul(MATRIX_A, MATRIX_B)

tensor([[19, 22],
        [43, 50]])

In [7]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [8]:
x.min()

tensor(0)

In [9]:
x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [10]:
x.type(float_32_tensor.dtype).mean()

tensor(45.)

In [11]:
torch.stack([x, x, x], dim=0)

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [12]:
torch.stack([x, x, x], dim=1)


tensor([[ 0,  0,  0],
        [10, 10, 10],
        [20, 20, 20],
        [30, 30, 30],
        [40, 40, 40],
        [50, 50, 50],
        [60, 60, 60],
        [70, 70, 70],
        [80, 80, 80],
        [90, 90, 90]])

In [13]:
torch.vstack([x,x,x])

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [14]:
torch.hstack([x,x,x])

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90,  0, 10, 20, 30, 40, 50, 60, 70,
        80, 90,  0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [15]:
a = torch.tensor([[1, 1], [1, 1]])
b = torch.tensor([[2, 2], [2, 2]])
a


tensor([[1, 1],
        [1, 1]])

In [16]:
torch.stack([a, b], dim=1)

tensor([[[1, 1],
         [2, 2]],

        [[1, 1],
         [2, 2]]])

In [17]:
torch.hstack([a, b])

tensor([[1, 1, 2, 2],
        [1, 1, 2, 2]])

In [18]:
x = torch.rand(2,3,5)
x.size()

torch.Size([2, 3, 5])

In [19]:
torch.permute(x, (2,0,1)).size()

torch.Size([5, 2, 3])

In [20]:
x

tensor([[[0.8338, 0.8514, 0.3116, 0.9507, 0.7936],
         [0.0119, 0.8852, 0.0669, 0.5006, 0.6201],
         [0.8679, 0.7544, 0.7609, 0.3970, 0.5900]],

        [[0.4838, 0.9663, 0.0383, 0.3984, 0.1807],
         [0.9759, 0.8316, 0.2962, 0.4889, 0.8855],
         [0.9438, 0.1704, 0.3374, 0.6886, 0.5987]]])

In [22]:
x.permute(2,0,1).shape

torch.Size([5, 2, 3])

In [28]:
x = torch.arange(1,10).reshape(1,3,3)
x.shape,x

(torch.Size([1, 3, 3]),
 tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]))

In [27]:
x[0][0][0]

tensor(1)

In [29]:
x[0,2,2]

tensor(9)

In [2]:
import torch
torch.cuda.is_available()

True

In [3]:
device = "cuda"if torch.cuda.is_available() else "cpu"

In [4]:
x = torch.tensor([1, 2, 3], dtype=torch.float32)

# 3. Move it to the GPU
x_gpu = x.to(device)

print(f"Tensor location: {x_gpu.device}")

Tensor location: cuda:0


In [5]:
import torch

# Create two large tensors directly on the GPU
a = torch.ones(1000, 1000).to("cuda")
b = torch.ones(1000, 1000).to("cuda")

# Perform matrix multiplication on the GPU
c = torch.matmul(a, b)

print(f"Calculation successful! Result shape: {c.shape}")
print(f"Device used: {c.device}")

Calculation successful! Result shape: torch.Size([1000, 1000])
Device used: cuda:0


In [6]:
cuda = torch.device('cuda')     # Default CUDA device
cuda0 = torch.device('cuda:0')
cuda2 = torch.device('cuda:2')  # GPU 2 (these are 0-indexed)

x = torch.tensor([1., 2.], device=cuda0)
# x.device is device(type='cuda', index=0)
y = torch.tensor([1., 2.]).cuda()
# y.device is device(type='cuda', index=0)

with torch.cuda.device(1):
    # allocates a tensor on GPU 1
    a = torch.tensor([1., 2.], device=cuda)

    # transfers a tensor from CPU to GPU 1
    b = torch.tensor([1., 2.]).cuda()
    # a.device and b.device are device(type='cuda', index=1)

    # You can also use ``Tensor.to`` to transfer a tensor:
    b2 = torch.tensor([1., 2.]).to(device=cuda)
    # b.device and b2.device are device(type='cuda', index=1)

    c = a + b
    # c.device is device(type='cuda', index=1)

    z = x + y
    # z.device is device(type='cuda', index=0)

    # even within a context, you can specify the device
    # (or give a GPU index to the .cuda call)
    d = torch.randn(2, device=cuda2)
    e = torch.randn(2).to(cuda2)
    f = torch.randn(2).cuda(cuda2)
    # d.device, e.device, and f.device are all device(type='cuda', index=2)

RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
