In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.0+cu124


In [4]:
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.2285, 0.1791, 0.8131, 0.1096],
         [0.5653, 0.2495, 0.6978, 0.7937],
         [0.6764, 0.2990, 0.1764, 0.2815]]])

In [5]:
random_tensor.shape

torch.Size([1, 3, 4])

In [6]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
float_32_tensor = torch.tensor([3.0, 2.0, 1.0], 
                                dtype=torch.float32, 
                                device="cpu", 
                                requires_grad=False)



In [10]:
MATRIX_A = torch.tensor([[1,2], [3,4]])
MATRIX_B = torch.tensor([[5,6], [7,8]])
torch.matmul(MATRIX_A, MATRIX_B)

tensor([[19, 22],
        [43, 50]])

In [12]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [14]:
x.min()

tensor(0)

In [16]:
x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [17]:
x.type(float_32_tensor.dtype).mean()

tensor(45.)